In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
data = pd.read_csv(r'weatherAUS.csv')

In [30]:
data=data[0:5000]

In [31]:
data['Location']='BadgerysCreek'

In [32]:
columns_to_check = ['Date','Rainfall' , 'Evaporation' , 'Sunshine' , 'WindGustDir' , 'WindGustDir' , 'WindGustSpeed' , 'WindDir9am' , 'WindDir3pm' , 'WindSpeed9am' ,'WindSpeed3pm' , 'Humidity9am' , 'Humidity3pm' , 'Pressure9am' , 'Pressure3pm' , 'Cloud9am' ,'Cloud3pm' ,'Temp9am' ,'Temp3pm' ,'RainTomorrow'] 
data_cleaned = data.dropna(subset=columns_to_check,how="all", inplace=True)

In [33]:
data_cleaned = data.dropna()
print(data_cleaned)

Empty DataFrame
Columns: [Date, Location, MinTemp, MaxTemp, Rainfall, Evaporation, Sunshine, WindGustDir, WindGustSpeed, WindDir9am, WindDir3pm, WindSpeed9am, WindSpeed3pm, Humidity9am, Humidity3pm, Pressure9am, Pressure3pm, Cloud9am, Cloud3pm, Temp9am, Temp3pm, RainToday, RainTomorrow]
Index: []

[0 rows x 23 columns]


In [34]:
data_cleaned

Empty DataFrame
Columns: [Date, Location, MinTemp, MaxTemp, Rainfall, Evaporation, Sunshine, WindGustDir, WindGustSpeed, WindDir9am, WindDir3pm, WindSpeed9am, WindSpeed3pm, Humidity9am, Humidity3pm, Pressure9am, Pressure3pm, Cloud9am, Cloud3pm, Temp9am, Temp3pm, RainToday, RainTomorrow]
Index: []

[0 rows x 23 columns]

In [35]:
data_cleaned = data.fillna(0)
data_cleaned.isnull().sum()

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [36]:
data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           5000 non-null   object 
 1   Location       5000 non-null   object 
 2   MinTemp        5000 non-null   float64
 3   MaxTemp        5000 non-null   float64
 4   Rainfall       5000 non-null   float64
 5   Evaporation    5000 non-null   float64
 6   Sunshine       5000 non-null   float64
 7   WindGustDir    5000 non-null   object 
 8   WindGustSpeed  5000 non-null   float64
 9   WindDir9am     5000 non-null   object 
 10  WindDir3pm     5000 non-null   object 
 11  WindSpeed9am   5000 non-null   float64
 12  WindSpeed3pm   5000 non-null   float64
 13  Humidity9am    5000 non-null   float64
 14  Humidity3pm    5000 non-null   float64
 15  Pressure9am    5000 non-null   float64
 16  Pressure3pm    5000 non-null   float64
 17  Cloud9am       5000 non-null   float64
 18  Cloud3pm

In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [38]:
ct=ColumnTransformer(transformers=[('transf',OneHotEncoder(),[0])],remainder='passthrough')
data_cleaned

Date       Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0     2008-12-01  BadgerysCreek     13.4     22.9       0.6          0.0   
1     2008-12-02  BadgerysCreek      7.4     25.1       0.0          0.0   
2     2008-12-03  BadgerysCreek     12.9     25.7       0.0          0.0   
3     2008-12-04  BadgerysCreek      9.2     28.0       0.0          0.0   
4     2008-12-05  BadgerysCreek     17.5     32.3       1.0          0.0   
...          ...            ...      ...      ...       ...          ...   
4995  2014-08-07  BadgerysCreek      1.6     19.3       0.0          0.0   
4996  2014-08-08  BadgerysCreek      2.3     18.4       0.0          0.0   
4997  2014-08-09  BadgerysCreek      2.4     21.3       0.0          0.0   
4998  2014-08-10  BadgerysCreek      4.5     22.6       0.0          0.0   
4999  2014-08-11  BadgerysCreek      1.6     14.7       0.0          0.0   

      Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
0          0.0           W           44.0          W  ...        71.0   
1          0.0         WNW           44.0        NNW  ...        44.0   
2          0.0         WSW           46.0          W  ...        38.0   
3          0.0          NE           24.0         SE  ...        45.0   
4          0.0           W           41.0        ENE  ...        82.0   
...        ...         ...            ...        ...  ...         ...   
4995       0.0          SW           30.0         SW  ...        56.0   
4996       0.0           E           22.0        WSW  ...        83.0   
4997       0.0         ENE           13.0        NNW  ...       100.0   
4998       0.0         WSW           35.0        WNW  ...        79.0   
4999       0.0         SSW           33.0         SW  ...        54.0   

      Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0            22.0       1007.7       1007.1       8.0       0.0     16.9   
1            25.0       1010.6       1007.8       0.0       0.0     17.2   
2            30.0       1007.6       1008.7       0.0       2.0     21.0   
3            16.0       1017.6       1012.8       0.0       0.0     18.1   
4            33.0       1010.8       1006.0       7.0       8.0     17.8   
...           ...          ...          ...       ...       ...      ...   
4995         33.0       1029.9       1027.2       0.0       0.0     12.0   
4996         54.0       1032.2       1029.3       0.0       0.0      9.3   
4997         37.0       1029.9       1024.4       0.0       0.0      8.6   
4998         28.0       1022.5       1017.9       0.0       0.0      9.6   
4999         38.0       1025.9       1024.6       0.0       0.0      9.7   

      Temp3pm  RainToday  RainTomorrow  
0        21.8         No            No  
1        24.3         No            No  
2        23.2         No            No  
3        26.5         No            No  
4        29.7         No            No  
...       ...        ...           ...  
4995     19.2         No            No  
4996     17.8         No            No  
4997     20.6         No            No  
4998     21.2         No            No  
4999     13.6         No            No  

[5000 rows x 23 columns]

In [39]:
data_cleaned.drop(['Date','WindGustDir','WindDir9am','WindDir3pm','RainToday'],inplace=True,axis=1)

In [40]:
x=data_cleaned.iloc[:,0:-1].values
y=data_cleaned.iloc[:,-1].values
y = y.astype(str)


In [41]:
x=np.array(ct.fit_transform(x))
x

array([[1.0, 13.4, 22.9, ..., 0.0, 16.9, 21.8],
       [1.0, 7.4, 25.1, ..., 0.0, 17.2, 24.3],
       [1.0, 12.9, 25.7, ..., 2.0, 21.0, 23.2],
       ...,
       [1.0, 2.4, 21.3, ..., 0.0, 8.6, 20.6],
       [1.0, 4.5, 22.6, ..., 0.0, 9.6, 21.2],
       [1.0, 1.6, 14.7, ..., 0.0, 9.7, 13.6]], dtype=object)

In [42]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()


y_encoded = label_encoder.fit_transform(y)


print(y_encoded)


[1 1 1 ... 1 1 1]


IMPORTING MODELS

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [44]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [45]:
lr = LogisticRegression()
rf = RandomForestClassifier()
svc = SVC()

In [46]:
lr.fit(x_train,y_train)

C:\Users\krish\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [47]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [48]:
svc.fit(x_train,y_train)

SVC()

Prediction using models

In [49]:
y_pred1 = lr.predict(x_test)
y_prob = lr.predict_proba(x_test)

In [50]:
y_pred2 = rf.predict(x_test)

In [51]:
y_pred3 = svc.predict(x_test)

CHECKING ACCURACY OF MODELS

In [52]:
from sklearn.metrics import accuracy_score,roc_curve,confusion_matrix

# the accuracy score nikal lo
accuracy1 = accuracy_score(y_test, y_pred1)
accuracy2 = accuracy_score(y_test, y_pred2)
accuracy3 = accuracy_score(y_test, y_pred3)

# accuracy score display krdo
print("Logistic Regression Accuracy:", accuracy1)
print("Random Forest Accuracy:", accuracy2)
print("SVM Accuracy:", accuracy3)



Logistic Regression Accuracy: 0.845
Random Forest Accuracy: 0.855
SVM Accuracy: 0.783


In [53]:
cf_mat = confusion_matrix(y_test, y_pred1)
cf_mat

array([[  5,   9,   0],
       [  1, 730,  52],
       [  0,  93, 110]], dtype=int64)

In [54]:
fpr,tpr,threshold=roc_curve(y_test, y_pred1)


ValueError: multiclass format is not supported